### ISSUE TITLE
example on main fails clicking on 'reactive form widgets' in navigation

### ISSUE THREAD

**Issue by runyaga** [joanpablo/reactive_forms#414]
using git main clicking on 'reactive native widgets' fails

```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Could not find a generator for route RouteSettings("/reactive-form-widgets", null) in the
_WidgetsAppState.
Make sure your root app widget has provided a way to generate
this route.
Generators for routes are searched for in the following order:
 1. For the "/" route, the "home" property, if non-null, is used.
 2. Otherwise, the "routes" table is used, if it has an entry for the route.
 3. Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not
handled by "home" and "routes".
 4. Finally if all else fails onUnknownRoute is called.
Unfortunately, onUnknownRoute was not set.

When the exception was thrown, this was the stack:
#0      _WidgetsAppState._onUnknownRoute.<anonymous closure> (package:flutter/src/widgets/app.dart:1442:9)
#1      _WidgetsAppState._onUnknownRoute (package:flutter/src/widgets/app.dart:1457:6)
#2      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:4235:37)
#3      NavigatorState.pushReplacementNamed (package:flutter/src/widgets/navigator.dart:4348:36)
#4      AppDrawer.build.<anonymous closure> (package:reactive_forms_example/drawer.dart:44:50)
#5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154:21)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311:5)
#9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:281:7)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167:27)
#11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492:20)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
#13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:439:11)
#14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
#18     _invoke1 (dart:ui/hooks.dart:186:13)
#19     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:433:7)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#12747
════════════════════════════════════════════════════════════════════════════════════════════════════

D/EGL_emulation( 4955): app_time_stats: avg=79.40ms min=1.14ms max=1241.88ms count=16
D/EGL_emulation( 4955): app_time_stats: avg=117.46ms min=1.04ms max=2631.16ms count=23
D/EGL_emulation( 4955): app_time_stats: avg=74.86ms min=1.09ms max=924.45ms count=13
Another exception was thrown: Could not find a generator for route RouteSettings("/reactive-form-widgets", null) in the
_WidgetsAppState.
```

**Comment by joanpablo** [comment]
Thanks @runyaga I will take a look.
